#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

domains_raw="$TMP_DIR/domains.raw"
ips_raw="$TMP_DIR/ips.raw"
touch "$domains_raw" "$ips_raw"
used_python=0
ADDRESS_LIST_NAME="${ADDRESS_LIST_NAME:-iran-streaming}"

find_python() {
  if [[ -n "${IRAN_STREAMING_PYTHON:-}" && -x "$IRAN_STREAMING_PYTHON" ]]; then
    printf '%s\n' "$IRAN_STREAMING_PYTHON"
  elif command -v python3 >/dev/null 2>&1; then
    command -v python3
  elif command -v python >/dev/null 2>&1; then
    command -v python
  elif command -v py >/dev/null 2>&1; then
    command -v py
  fi
}

normalize_domains() {
  tr '[:upper:]' '[:lower:]' |
    sed -E 's#^https?://##; s#/.*$##; s/:.*$//; s/^\*\.//; s/[[:space:]]//g' |
    sed '/^$/d; /^#/d'
}

public_ipv4_filter() {
  awk -F. '
    NF == 4 && $1 ~ /^[0-9]+$/ && $2 ~ /^[0-9]+$/ && $3 ~ /^[0-9]+$/ && $4 ~ /^[0-9]+$/ {
      a=$1+0; b=$2+0; c=$3+0; d=$4+0
      if (a>255 || b>255 || c>255 || d>255) next
      if (a==0 || a==10 || a==127 || a>=224) next
      if (a==100 && b>=64 && b<=127) next
      if (a==169 && b==254) next
      if (a==172 && b>=16 && b<=31) next
      if (a==192 && b==168) next
      if (a==192 && b==0 && c==0) next
      if (a==192 && b==0 && c==2) next
      if (a==198 && (b==18 || b==19)) next
      if (a==198 && b==51 && c==100) next
      if (a==203 && b==0 && c==113) next
      print
    }
  '
}

normalize_domains < "$ROOT_DIR/config/domains.txt" >> "$domains_raw"

PYTHON_BIN="$(find_python || true)"
if [[ -n "$PYTHON_BIN" ]]; then
  if "$PYTHON_BIN" "$ROOT_DIR/scripts/discover-iran-streaming.py"; then
    used_python=1
  else
    echo "warning: Python discovery failed; using basic domain discovery only" >&2
  fi
else
  echo "warning: Python was not found; using basic domain discovery only" >&2
fi

if [[ -s "$ROOT_DIR/iran-streaming-domains.txt" ]]; then
  cat "$ROOT_DIR/iran-streaming-domains.txt" >> "$domains_raw"
fi

normalize_domains < "$domains_raw" | sort -u > "$ROOT_DIR/iran-streaming-domains.txt"

if [[ "$used_python" != 1 || ! -s "$ROOT_DIR/iran-streaming-hosts.txt" ]]; then
  cp "$ROOT_DIR/iran-streaming-domains.txt" "$ROOT_DIR/iran-streaming-hosts.txt"
fi

if [[ "$used_python" != 1 ]]; then
  while IFS= read -r host; do
    [[ -z "$host" ]] && continue
    if command -v dig >/dev/null 2>&1; then
      dig +short A "$host" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' >> "$ips_raw" || true
    elif command -v nslookup >/dev/null 2>&1; then
      nslookup "$host" 2>/dev/null | awk '/^Address: / {print $2}' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' >> "$ips_raw" || true
    fi
  done < "$ROOT_DIR/iran-streaming-domains.txt"
fi

if [[ -s "$ROOT_DIR/iran-streaming-ips.txt" ]]; then
  cat "$ROOT_DIR/iran-streaming-ips.txt" >> "$ips_raw"
fi

sort -u "$ips_raw" | public_ipv4_filter | sort -u > "$ROOT_DIR/iran-streaming-ips.txt"
sed 's#$#/32#' "$ROOT_DIR/iran-streaming-ips.txt" > "$ROOT_DIR/iran-streaming-prefixes.txt"

{
  echo '# Generated by scripts/build-iran-streaming.sh'
  echo "# Address list: $ADDRESS_LIST_NAME"
  echo '# Uses discovered FQDN entries so RouterOS resolves current CDN IPs dynamically.'
  echo "/ip firewall address-list remove [find list=$ADDRESS_LIST_NAME]"
  while IFS= read -r host; do
    [[ -z "$host" ]] && continue
    echo "/ip firewall address-list add list=$ADDRESS_LIST_NAME address=$host comment=\"iran-streaming-route-list-fqdn\""
  done < "$ROOT_DIR/iran-streaming-domains.txt"
} > "$ROOT_DIR/mikrotik-iran-streaming-address-list.rsc"

echo "domains: $(wc -l < "$ROOT_DIR/iran-streaming-domains.txt")"
echo "hosts: $(wc -l < "$ROOT_DIR/iran-streaming-hosts.txt")"
echo "ips: $(wc -l < "$ROOT_DIR/iran-streaming-ips.txt")"
