#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

domains_raw="$TMP_DIR/domains.raw"
ips_raw="$TMP_DIR/ips.raw"
touch "$domains_raw" "$ips_raw"

normalize_domains() {
  tr '[:upper:]' '[:lower:]' |
    sed -E 's#^https?://##; s#/.*$##; s/^\*\.//; s/[[:space:]]//g' |
    sed '/^$/d'
}

normalize_domains < "$ROOT_DIR/config/domains.txt" >> "$domains_raw"

if command -v curl >/dev/null 2>&1 && command -v jq >/dev/null 2>&1; then
  curl -fsSL "https://crt.sh/?q=%25.filimo.com&output=json" |
    jq -r '.[].name_value?' |
    sed 's/\\n/\n/g' |
    normalize_domains >> "$domains_raw" || true
fi

sort -u "$domains_raw" |
  grep -E '(^|\.)(filimo\.com|aparat\.com)$' > "$ROOT_DIR/filimo-domains.txt"

cp "$ROOT_DIR/filimo-domains.txt" "$ROOT_DIR/filimo-hosts.txt"

while IFS= read -r host; do
  [[ -z "$host" ]] && continue
  if command -v dig >/dev/null 2>&1; then
    dig +short A "$host" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' >> "$ips_raw" || true
  elif command -v nslookup >/dev/null 2>&1; then
    nslookup "$host" | awk '/^Address: / {print $2}' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' >> "$ips_raw" || true
  fi
done < "$ROOT_DIR/filimo-hosts.txt"

sort -u "$ips_raw" > "$ROOT_DIR/filimo-ips.txt"
sed 's#$#/32#' "$ROOT_DIR/filimo-ips.txt" > "$ROOT_DIR/filimo-prefixes.txt"

{
  echo '# Generated by scripts/build-filimo.sh'
  echo '# Address list: filimo'
  echo '/ip firewall address-list remove [find list=filimo]'
  while IFS= read -r ip; do
    [[ -z "$ip" ]] && continue
    echo "/ip firewall address-list add list=filimo address=$ip comment=\"filimo-route-list\""
  done < "$ROOT_DIR/filimo-ips.txt"
} > "$ROOT_DIR/mikrotik-filimo-address-list.rsc"

echo "domains: $(wc -l < "$ROOT_DIR/filimo-domains.txt")"
echo "ips: $(wc -l < "$ROOT_DIR/filimo-ips.txt")"
