#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

domains_raw="$TMP_DIR/domains.raw"
ips_raw="$TMP_DIR/ips.raw"
touch "$domains_raw" "$ips_raw"

normalize_domains() {
  tr '[:upper:]' '[:lower:]' |
    sed -E 's#^https?://##; s#/.*$##; s/^\*\.//; s/[[:space:]]//g' |
    sed '/^$/d'
}

public_ipv4_filter() {
  awk -F. '
    NF == 4 && $1 ~ /^[0-9]+$/ && $2 ~ /^[0-9]+$/ && $3 ~ /^[0-9]+$/ && $4 ~ /^[0-9]+$/ {
      a=$1+0; b=$2+0; c=$3+0; d=$4+0
      if (a>255 || b>255 || c>255 || d>255) next
      if (a==0 || a==10 || a==127 || a>=224) next
      if (a==100 && b>=64 && b<=127) next
      if (a==169 && b==254) next
      if (a==172 && b>=16 && b<=31) next
      if (a==192 && b==168) next
      if (a==192 && b==0 && c==0) next
      if (a==192 && b==0 && c==2) next
      if (a==198 && (b==18 || b==19)) next
      if (a==198 && b==51 && c==100) next
      if (a==203 && b==0 && c==113) next
      print
    }
  '
}

normalize_domains < "$ROOT_DIR/config/domains.txt" >> "$domains_raw"

if command -v curl >/dev/null 2>&1 && command -v jq >/dev/null 2>&1; then
  curl -fsSL "https://crt.sh/?q=%25.filimo.com&output=json" |
    jq -r '.[].name_value?' |
    sed 's/\\n/\n/g' |
    normalize_domains >> "$domains_raw" || true
fi

sort -u "$domains_raw" |
  grep -E '(^|\.)(filimo\.com|aparat\.com)$' > "$ROOT_DIR/filimo-domains.txt"

cp "$ROOT_DIR/filimo-domains.txt" "$ROOT_DIR/filimo-hosts.txt"

while IFS= read -r host; do
  [[ -z "$host" ]] && continue
  if command -v dig >/dev/null 2>&1; then
    dig +short A "$host" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' >> "$ips_raw" || true
  elif command -v nslookup >/dev/null 2>&1; then
    nslookup "$host" | awk '/^Address: / {print $2}' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' >> "$ips_raw" || true
  fi
done < "$ROOT_DIR/filimo-hosts.txt"

sort -u "$ips_raw" | public_ipv4_filter > "$ROOT_DIR/filimo-ips.txt"
sed 's#$#/32#' "$ROOT_DIR/filimo-ips.txt" > "$ROOT_DIR/filimo-prefixes.txt"

{
  echo '# Generated by scripts/build-filimo.sh'
  echo '# Address list: filimo'
  echo '/ip firewall address-list remove [find list=filimo]'
  while IFS= read -r ip; do
    [[ -z "$ip" ]] && continue
    echo "/ip firewall address-list add list=filimo address=$ip comment=\"filimo-route-list\""
  done < "$ROOT_DIR/filimo-ips.txt"
} > "$ROOT_DIR/mikrotik-filimo-address-list.rsc"

echo "domains: $(wc -l < "$ROOT_DIR/filimo-domains.txt")"
echo "ips: $(wc -l < "$ROOT_DIR/filimo-ips.txt")"
